### ISSUE TITLE
Misleading Title and Unrealistic Objective

### ISSUE THREAD

**Issue by JASory** [BDR-Pro/PrimeShorRustPackage#1]
This is clearly not Shor's algorithm, it's a very poor implementation of a trial division algorithm. Trial division can't even efficiently factor u128's so implementing it for anything larger is simply relying on a gamble that the integer just happens to only have small factors. 

Implementing Shor's algorithm is impractical for classical computers, and still useless even in current quantum computers.

**Comment by BDR-Pro** [comment]
Thank you a lot my brother

I am still learning and I do not know that 🫶🏻 i thought it was prome shor because that's what we learned at a quantum computing course
Thank you once again
